---
name: pr

on:
  pull_request:

jobs:
  golint:
    uses: hostwithquantum/github-workflows/.github/workflows/golint.yml@main
    secrets:
      DOWNLOAD_PACKAGE_TOKEN: ${{ secrets.DOWNLOAD_PACKAGE_TOKEN }}

  gotest:
    uses: hostwithquantum/github-workflows/.github/workflows/gotest.yml@main
    secrets:
      DOWNLOAD_PACKAGE_TOKEN: ${{ secrets.DOWNLOAD_PACKAGE_TOKEN }}
